### ISSUE TITLE
Error view form

### ISSUE THREAD

**Issue by XtrullorEas** [faris17/filament3#1]
I had a problem creating the form, but then checking the repository I found that I had to create the compact column, this already works, after creating the form when I click on the form, where the metrics are, I get this error.

**could not find driver**
https://flareapp.io/share/KPgW4YZP

I would appreciate if there is a place where you can help me with this error, I have a lot of problems installing the bolt module as it is in the demo.

**Comment by faris17** [comment]
problem solved sir?
